apiVersion: v1
kind: Secret
metadata:
    name: aws-secret
type: Opaque
data:
    credentials:

# Run the command
#  cat ~/.aws/credentials | head -n 3 | base64
# to add to what's needed in Credentials.