apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-svc
  labels:
    app: frontend-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-svc
  template:
    metadata:
      labels:
        app: frontend-svc
    spec:
      containers:
      - name: frontend-svc
        image: gonzaga626/05-front-end
        ports:
        - containerPort: 80